# serverless.yml

service: fastify-lambda
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
functions:
  fastify_lambda:
    handler: src/fastify_lambda.handler
    events:
    - http:
        path: /
        method: post
        cors: true
    - http:
        path: /
        method: get
        cors: true
    - http:
        path: /graphql
        method: post
        cors: true
    - http:
        path: /graphql
        method: get
        cors: true