# serverless.yml

service: federation-service-comments
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
functions:
  comments:
    handler: comments.commentsHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true